// vue-app/src/App.vue
<template>
	<section>
		<div id="actions">
			<button id="create1000" @click.prevent="create(1000)">Criar 1,000 linhas</button>
			<button id="create10000" @click.prevent="create(10000)">Criar 10,000 linhas</button>
			<button id="append1000" @click.prevent="append(1000)">Inserir 1,000 linhas</button>
			<button id="update" @click.prevent="update">Atualizar linhas</button>
			<button id="swap" @click.prevent="swap">Trocar linhas</button>
			<button id="clear" @click.prevent="clear">Limpar tabela</button>
		</div>
		<table id="results">
			<tbody>
				<!-- https://v3.vuejs.org/api/directives.html#v-memo -->
				<tr
					v-for="{ id, text } in rows"
					v-memo="[text, id === selected]"
					:key="id"
					:class="{ selected: id === selected }"
				>
					<td>{{ id }}</td>
					<td>
						<a @click.prevent="select(id)">{{ text }}</a>
					</td>
					<td>
						<a @click.prevent="remove(id)">remover</a>
					</td>
				</tr>
			</tbody>
		</table>
	</section>
</template>

<script setup>
import { ref } from "vue";

import { generateData } from "angular-react-vue-benchmark";

const selected = ref();
const rows = ref([]);

const create = (n) => {
	rows.value = generateData(n);
};

const append = (n) => {
	rows.value.push(...generateData(n));
};

const update = () => {
	const _rows = [...rows.value];
	for (let index = 0; index < _rows.length; index += 10) {
		_rows[index].text += " (atualizado)";
	}
	rows.value = _rows;
};

const swap = () => {
	const _rows = [...rows.value];
	if (_rows.length > 1) {
		[_rows[0], _rows[_rows.length - 1]] = [_rows[_rows.length - 1], _rows[0]];
		rows.value = _rows;
	}
};

const clear = () => {
	rows.value = [];
};

const select = (id) => {
	selected.value = id;
};

const remove = (id) => {
	// https://v3.vuejs.org/guide/list.html#array-change-detection
	rows.value.splice(
		rows.value.findIndex((row) => row.id === id),
		1,
	);
};
</script>

<style>
@import url("~angular-react-vue-benchmark/styles.css");
</style>

// react-app/src/App.js
import { useState } from "react";

import { generateData } from "angular-react-vue-benchmark";
import "angular-react-vue-benchmark/styles.css";

const App = () => {
	const [selected, setSelected] = useState();
	const [rows, setRows] = useState([]);

	const create = (event, n) => {
		event.preventDefault();
		setRows(generateData(n));
	};

	const append = (event, n) => {
		event.preventDefault();
		setRows([...rows, ...generateData(n)]);
	};

	const update = (event) => {
		event.preventDefault();
		const _rows = [...rows];
		for (let index = 0; index < _rows.length; index += 10) {
			_rows[index].text += " (atualizado)";
		}
		setRows(_rows);
	};

	const swap = (event) => {
		event.preventDefault();
		const _rows = [...rows];
		if (_rows.length > 1) {
			[_rows[0], _rows[_rows.length - 1]] = [_rows[_rows.length - 1], _rows[0]];
			setRows(_rows);
		}
	};

	const clear = (event) => {
		event.preventDefault();
		setRows([]);
	};

	const select = (event, id) => {
		event.preventDefault();
		setSelected(id);
	};

	const remove = (event, id) => {
		event.preventDefault();
		setRows(rows.filter((row) => row.id !== id));
	};

	return (
		<section>
			<div id="actions">
				<button id="create1000" onClick={(event) => create(event, 1000)}>
					Criar 1,000 linhas
				</button>
				<button id="create10000" onClick={(event) => create(event, 10000)}>
					Criar 10,000 linhas
				</button>
				<button id="append1000" onClick={(event) => append(event, 1000)}>
					Inserir 1,000 linhas
				</button>
				<button id="update" onClick={update}>
					Atualizar linhas
				</button>
				<button id="swap" onClick={swap}>
					Trocar linhas
				</button>
				<button id="clear" onClick={clear}>
					Limpar tabela
				</button>
			</div>
			<table id="results">
				<tbody>
					{rows.map(({ id, text }) => (
						<tr key={id} className={id === selected ? "selected" : ""}>
							<td>{id}</td>
							<td>
								<a onClick={(event) => select(event, id)}>{text}</a>
							</td>
							<td>
								<a onClick={(event) => remove(event, id)}>remover</a>
							</td>
						</tr>
					))}
				</tbody>
			</table>
		</section>
	);
};

export default App;
